language: objective-c
osx_image: xcode9.1

script:
  - xcodebuild clean build test -project KalmanFilter.xcodeproj -scheme KalmanFilter -destination 'platform=iOS Simulator,name=iPhone 8'

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
